configurations.all {
	resolutionStrategy {
		force group: "com.liferay.portal", name: "com.liferay.portal.test", version: "7.1.0"
	}
}

dependencies {
	testIntegrationImplementation group: "com.liferay.portal", name: "release.dxp.api"
	testIntegrationImplementation project(":modules:myblue-portal-mobileapp-portlet:myblue-portal-mobileapp-portlet-api")
	testIntegrationImplementation project(":modules:myblue-portal-mobileapp-portlet:myblue-portal-mobileapp-portlet-client")
}